- name: Halloween collection 🎃
  remodels:
    - name: Halloween 14-15
      path: Hangars/Halloween/Halloween-14-15
      download: https://forblitz.ru/wp-content/uploads/2024/06/hangar_helloween2014-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2014/18109
    - name: Halloween 15-16
      path: Hangars/Halloween/Halloween-15-16
      download: https://forblitz.ru/wp-content/uploads/2023/12/hangar_helloween_2016-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2016/18416
    - name: Halloween 16-17
      path: Hangars/Halloween/Halloween-16-17
      download: https://forblitz.ru/wp-content/uploads/2023/12/hangar_hell_2017-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2017/18429
    - name: Halloween 17-18
      path: Hangars/Halloween/Halloween-17-18
      download: https://forblitz.ru/wp-content/uploads/2023/12/hangar_hell_2018_20-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2018-2020/18436
    - name: Halloween 19-20
      path: Hangars/Halloween/Halloween-19-20
      download: https://forblitz.ru/wp-content/uploads/2024/11/hangar_halloween2019_uni_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2019/18443
    - name: Halloween 20-21
      path: Hangars/Halloween/Halloween-20-21
      download: https://forblitz.ru/wp-content/uploads/2023/12/hangar_hell_21-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2021/18450
    - name: Halloween 21-22
      path: Hangars/Halloween/Halloween-21-22
      download: https://forblitz.ru/wp-content/uploads/2023/12/hangar_hell_22-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-khellouin-2022/18457
    - name: Stock
      path: Hangars/Stock
- name: Xmas collection 🎄
  remodels:
    - name: Xmas 2015
      path: Hangars/Xmas/Xmas-2015
      download: https://drive.usercontent.google.com/download?id=1w7-aGbTHsgZo8NsxHdzwLL99vLMcovmS&export=download&authuser=1&confirm=t&uuid=4b57305b-c00b-4620-8bb6-469598b4ddb6&at=APvzH3rcf4chI9VgjgroA0MFwfz4:1736156728219
      source: not provided
    - name: Xmas 2020
      path: Hangars/Xmas/Xmas-2020
      download: https://drive.usercontent.google.com/download?id=1ec6wt5q07KXte88vxuH9z9hvKDlIoUHQ&export=download&authuser=1&confirm=t&uuid=1a012d94-7cfb-40e1-8c1e-3060878002d9&at=APvzH3pcG9IOwlXpN3Ydm6uy9BtY:1735341658050
      source: not provided
    - name: Xmas 2021
      path: Hangars/Xmas/Xmas-2021
      download: https://forblitz.ru/wp-content/uploads/2025/01/hangar_2021_ny_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/new-years-hangar-2021/21548
    - name: Stock
      path: Hangars/Stock
- name: Past hangars 🗃️
  remodels:
    - name: Premium 2018
      path: Hangars/Past/Premium-2018
      download: https://forblitz.ru/wp-content/uploads/2024/07/hangar_prem_2018-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar/20302
    - name: Square
      path: Hangars/Past/Square
      download: https://forblitz.ru/wp-content/uploads/2024/05/hangar_9may_2015-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-9-maya-2015-2017/19928
    - name: Forest
      path: Hangars/Past/Forest
      download: https://forblitz.ru/wp-content/uploads/2024/05/hangar_9may_2020-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/angar-v-lesu-9-maya-2020/19939
    - name: First hangar
      path: Hangars/Past/First
      download: https://forblitz.ru/wp-content/uploads/2024/07/hangarlow4-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/old-hangar/17279
    - name: Stock
      path: Hangars/Stock
- name: Game maps 🗺️
  remodels:
  - name: Midlburg
    path: Hangars/Maps/Midlburg
    download: https://forblitz.ru/wp-content/uploads/2023/09/midlburg-1_pc_wg.zip
    source: https://forblitz.ru/modifications/hangars/hangar_midlburg_qq/17771
  - name: Holland
    path: Hangars/Maps/Holland
    download: https://forblitz.ru/wp-content/uploads/2024/09/holland_new-1_pc_wg.zip
    source: https://forblitz.ru/modifications/hangars/angar-gollandiya/11470
  - name: Mines
    path: Hangars/Maps/Mines
    download: https://drive.usercontent.google.com/download?id=18z2LYLysugJp_06taV2h_TMq4nQjFS8o&export=download&authuser=1&confirm=t&uuid=6ee9c685-9592-4b46-8076-615c3b9b7192&at=APvzH3rcn4p6zb7-RFth6MfnoTwB:1735811755203
    source: https://discord.com/channels/174448788436549632/254137952215498762/1131908995813232740
  - name: Stock
    path: Hangars/Stock
- name: Custom hangars ✏️
  remodels:
    - name: Cave
      path: Hangars/Custom/Cave
      download: https://forblitz.ru/wp-content/uploads/2023/10/hangar_peshera_igr-1_pc_wg.zip
      source: https://forblitz.ru/modifications/hangars/hangar-igr-qh/16491
    - name: 28 Days Later
      path: Hangars/Custom/28DaysLater
      download: https://blitz-mods.com/mod/hangars/28-days-later-32/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/hangars/28-days-later-32 
    - name: Spookwood Forest
      path: Hangars/Custom/Spookwood-Forest
      download: https://blitz-mods.com/mod/hangars/spookwood-forest-29/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/hangars/spookwood-forest-29
    - name: Minimalistic
      path: Hangars/Custom/Minimalistic
      download: https://blitz-mods.com/mod/hangars/minimalistic-1-52/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/hangars/minimalistic-1-52
    - name: Stock
      path: Hangars/Stock
