Custom:
  Recolored-Sight:
    path: Sights/
    download: https://blitz-mods.com/mod/sights/recolored-default-sight-by-muzmods-147/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/recolored-default-sight-by-muzmods-147

  Type-O: 
    download: https://blitz-mods.com/mod/sights/type-o-2/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/type-o-2

  Torquoise-v3: 
    download: https://blitz-mods.com/mod/sights/turquosie-v3-14/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/turquosie-v3-14

  White-Ready: 
    download: https://blitz-mods.com/mod/sights/white-ready-34/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/white-ready-34

  Green-Ready:
    download: https://blitz-mods.com/mod/sights/ready-by-andre-v-16/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/ready-by-andre-v-16#google_vignette

  Green+:
    download: https://blitz-mods.com/mod/sights/green-1/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/green-1

  Taipan-2: 
    download: https://blitz-mods.com/mod/sights/sight-taipan-2-93/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/sight-taipan-2-93

  Modern-Warfare: 
      download: https://blitz-mods.com/mod/sights/modern-warfare-12/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/sights/modern-warfare-12     

WOT-alike:
  WOT-Aimpoint-classic: 
    download: https://blitz-mods.com/mod/sights/sight-from-world-of-tanks-for-wotblitz-71/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sights/sight-from-world-of-tanks-for-wotblitz-71
  
  WOT-Aimpoint-sh0tnik:
    download: https://forblitz.ru/wp-content/uploads/2023/10/aim_point_bb_sh0tnik_10_6_7_pc.zip
    source: https://forblitz.ru/modifications/scopes/pritsel-v-vide-tochki-iz-bb-kak-u-sh0tnika/14657
  
  WOT-Aimpoint-korbendallas:
    download: https://forblitz.ru/wp-content/uploads/2023/10/aim_point_bb_korbendallas_pc_10_3.zip
    source: https://forblitz.ru/modifications/scopes/pritsel-v-vide-tochki-iz-bb-kak-u-korben-dallasa/14860
  
  WOT-Aimpoint-amway921:
    download: https://forblitz.ru/wp-content/uploads/2023/10/aim_crosshair_bb_amway921_pc_10_3.zip
    source: https://forblitz.ru/modifications/scopes/pritsel-v-vide-perekrestiya-iz-bb-kak-u-amway921/15024
  
  WOT-Aimpoint-thebarbarian:
    download: https://forblitz.ru/wp-content/uploads/2023/10/aim_point_bb_the_barbarian_10_6_7_pc_lesta.zip
    source: https://forblitz.ru/modifications/scopes/pritsel-v-vide-kruga-iz-bb-kak-u-the_barbariana/14940
  
  WOT-Aimpoint-lebwa:
    download: https://forblitz.ru/wp-content/uploads/2023/10/bb_aim_a-shaped_lebwa_pc_10_3.zip
    source: https://forblitz.ru/modifications/scopes/a-obraznyi-pritsel-iz-bb-kak-u-levshi/16194
