#EUROPEAN

#heavy
- name: Škoda T 56
  type: Heavy
  tier: VIII
  nation: Czechia 🦁
  remodels:
    - name: Hurikán
      path: Tanks/European/Škoda-T56/Hurikán
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-56-hurikan-222/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-56-hurikan-222
    - name: Projekt ION
      path: Tanks/European/Škoda-T56/Projekt-ION
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t56-project-ion-247/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t56-project-ion-247
    - name: Stock
      path: Tanks/European/Škoda-T56/Stock

#mediums
- name: "Škoda T 27"
  type: Medium
  tier: VIII
  nation: Czechia 🦁
  remodels:
    - name: Enhanced
      path: Tanks/European/Škoda-T27/Enhanced
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-27-258/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-27-258
    - name: Stock
      path: Tanks/European/Škoda-T27/Stock

# France:
#   AMX-50B:
#     Charlesmartel:
#       download: https://drive.usercontent.google.com/download?id=1q02Uj4UX66ZFKjbTwulSn-Xec5fLHOt2&export=download&authuser=1&confirm=t&uuid=7bdcaa42-330a-4b90-bfa7-ca1ac645e6d7&at=AENtkXZVbEWPJbB6IKxIyRFTowb-:1730993378473
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1069655296995242004

- name: B-C 25 t
  type: Light
  tier: X
  nation: France 🥖
  remodels:
    - name: Arlequin Ter
      path: Tanks/France/B-C_25t/Arlequin-Ter
      download: https://blitz-mods.com/mod/remodelings/remodeling-bat-chatillon-25t-arlequin-ter-217/download/pc-wg/file?_token=x=0
      source: https://tinyurl.com/blitzmods
    - name: Marengo
      path: Tanks/France/B-C_25t/Marengo
      download: https://forblitz.ru/wp-content/uploads/2022/08/updated_batchat_25t_marengo_sadabsolution_steam.zip
      source: https://tinyurl.com/forblitz-marengo
    - name: Ignis Purgatio
      path: Tanks/France/B-C_25t/Ignis-Purgatio
      download: https://forblitz.ru/wp-content/uploads/2022/10/batchat_ignis_steam.zip
      source: https://tinyurl.com/ignis-purgatio
    - name: Foudre
      path: Tanks/France/B-C_25t/Foudre
      download: https://forblitz.ru/wp-content/uploads/2024/04/bat_chatillon25t_fdr_pc.zip
      source: https://tinyurl.com/bc25t-foudre
    - name: Stock
      path: Tanks/France/B-C_25t/Stock

- name: Foch 155
  type: Td
  tier: X
  nation: France 🥖
  remodels:
    - name: Eglantier
      path: Tanks/France/Foch-155/Eglantier
      download: https://blitz-mods.com/mod/remodelings/remodeling-foch-155-eglantier-253/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-foch-155-eglantier-253
    - name: Stock
      path: Tanks/France/Foch-155/Stock

# Mediums
- name: Defender Mk.1
  type: Medium
  tier: VIII
  nation: GB 🌧️
  remodels:
    - name: Realistic
      path: Tanks/GB/Defender-Mk1/Realistic
      download: https://blitz-mods.com/mod/skins/skin-centurion-mkiii-ep-defender-167/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/skins/skin-centurion-mkiii-ep-defender-167
    - name: Stock
      path: Tanks/GB/Defender-Mk1/Stock

# Lights
- name: Vickers Light
  type: Light
  tier: X
  nation: GB 🌧️
  remodels:
    - name: Concept 5 The Unknown
      path: Tanks/GB/Vickers-Light/Concept-5-TheUnknown
      download: https://forblitz.ru/wp-content/uploads/2024/11/vikclight_concept5_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-concept-5-the-unknown/21206
    - name: Stock
      path: Tanks/GB/Vickers-Light/Stock

#TD's
- name: FV4005
  type: Td
  tier: X
  nation: GB 🌧️
  remodels:
    - name: King Flavius
      path: Tanks/GB/FV4005/King-Flavius
      download: https://blitz-mods.com/mod/remodelings/fv-4005-king-favius-259/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/fv-4005-king-favius-259
    - name: Thunderchild
      path: Tanks/GB/FV4005/Thunderchild
      download: https://forblitz.ru/wp-content/uploads/2024/03/4005_thunderchild_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/animirovannyi-remodeling-fv4005-ditya-gro/19416
    - name: Galahad
      path: Tanks/GB/FV4005/Galahad
      download: https://forblitz.ru/wp-content/uploads/2022/02/fv4005_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-gb83-4005-hd/10768
    - name: Stock
      path: Tanks/GB/FV4005/Stock
- name: FV215b 183
  tier: X
  nation: GB 🌧️
  remodels:
    - name: Tesla
      path: Tanks/GB/FV215b-183/Tesla
      download: https://forblitz.ru/wp-content/uploads/2023/12/fv215b183_tesla_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-fv215b-183/18768
    - name: Stock
      path: Tanks/GB/FV215b-183/Stock

# USSR:
#Heavy

- name: Obj. 268
  type: Td
  tier: X
  nation: USSR 🐻
  remodels:
    - name: Svyatogor
      path: Tanks/USSR/Obj.268/Svyatogor
      download: https://forblitz.ru/wp-content/uploads/2024/01/obj268_svyatogor_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-obekt-268-svyatogor/18980
    - name: Alyosha Popovich
      path: Tanks/USSR/Obj.268/AlyoshaPopovich
      download: https://forblitz.ru/wp-content/uploads/2024/01/obj268_alesha_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-obekt-268-alesha-popovich/19012
    - name: Stock
      path: Tanks/USSR/Obj.268/Stock
#   T-100LT:
#     Enhanced:
#       path: Tanks/USSR/T-100-LT/Enhanced/
#       download: https://drive.usercontent.google.com/download?id=1NJDaRzHvJY47Z69wTE_zqo7qwtxxxj7h&export=download&authuser=1&confirm=t&uuid=a6a51793-7d8a-46e6-b818-4377a324038f&at=AENtkXZ8rQFHRlrQeYgMq4Jhl9cZ:1730984861744
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1076705953262620733
#     Gyurza:
#       path: Tanks/USSR/T-100-LT/Gyurza/
#       download: https://forblitz.ru/wp-content/uploads/2023/12/t100lt_forblitz_pc.zip
#       source: https://forblitz.ru/modifications/remodelings/remodeling-t-100-lt-giurza/18808
#     Stock:
#       path: Tanks/USSR/T-100-LT/Stock/

# USA

# Heavy

#   T49:
#     Revenant:
#       download: ttps://drive.usercontent.google.com/download?id=1Osd9ShPOMmo5bQJnIbrk4V0eOvNW6pNV&export=download&authuser=0&confirm=t&uuid=1d38fb20-7343-49ab-a472-75b788541958&at=AENtkXb3Lpn9jO3poQl1YXPR3wGf:1730886397473
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1011710957346619432
