#EUROPEAN

#heavy
- name: Kranvagn
  type: Heavy
  tier: X
  nation: Sweden 🫎
  remodels:
    - name: Trettonde
      path: Tanks/European/Kranvagn/Trettonde
      download: https://blitz-mods.com/mod/remodelings/kranvagn-trettonde-240/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/kranvagn-trettonde-240
    - name: Trettonde addon
      path: Tanks/European/Kranvagn/Trettonde-addon
      download: https://drive.usercontent.google.com/download?id=15VT6uOn1YO4K2vK4mtQnKnK5c3PjBQYr&export=download&authuser=1&confirm=t&uuid=4eb64303-1714-416d-9a4f-e3060e8dd6ab&at=AENtkXb4XJR4MQ1eOIX5d3L3fGTs:1731154689785
      source: https://discordapp.com/channels/1122455294988001363/1122581505693208596/1291021627689013260
    - name: "Hjälpkran"
      path: "Tanks/European/Kranvagn/Hjälpkran"
      download: https://forblitz.ru/wp-content/uploads/2023/02/kran4ik_forblitz_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-kranvagn-kran4ik/16257
    - name: Stock
      path: Tanks/European/Kranvagn/Stock
- name: Škoda T 56
  type: Heavy
  tier: VIII
  nation: Czechia 🦁
  remodels:
    - name: Hurikán
      path: Tanks/European/Škoda-T56/Hurikán
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-56-hurikan-222/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-56-hurikan-222
    - name: Projekt ION
      path: Tanks/European/Škoda-T56/Projekt-ION
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t56-project-ion-247/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t56-project-ion-247
    - name: Stock
      path: Tanks/European/Škoda-T56/Stock

#mediums
- name: "Škoda T 27"
  type: Medium
  tier: VIII
  nation: Czechia 🦁
  remodels:
    - name: Enhanced
      path: Tanks/European/Škoda-T27/Enhanced
      download: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-27-258/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-skoda-t-27-258
    - name: Stock
      path: Tanks/European/Škoda-T27/Stock

#GERMAN

#heavy
- name: E 100
  type: Heavy
  tier: X
  nation: German 🍺
  remodels:
    - name: Deus Ex
      path: Tanks/German/E-100/Deus-Ex
      download: https://forblitz.ru/wp-content/uploads/2022/08/update_e100_deusex_sadabsolution_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-deus-ex/13913
    - name: Klarer Himmel
      path: Tanks/German/E-100/Klarer-Himmel
      download: https://forblitz.ru/wp-content/uploads/2022/06/e100nem-9_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-e100-nemesis/12071
    - name: Rote Grundierung
      path: Tanks/German/E-100/Rote-Grundierung
      download: https://blitz-mods.com/mod/remodelings/remodeling-e-100-rote-grundierung-269/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-e-100-rote-grundierung-269
    - name: Nemesis
      path: Tanks/German/E-100/Nemesis
      download: https://forblitz.ru/wp-content/uploads/2023/06/e100_pinny_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-e-100-nemesis/17180
    - name: Nemesis addon
      path: Tanks/German/E-100/Nemesis-addon
      download: https://drive.usercontent.google.com/download?id=1kUrgbOj3B9sK0MiCFpbeTonvE_dmdkb9&export=download&authuser=1&confirm=t&uuid=085afa3a-5257-4b5b-b13b-7c2861bf954f&at=AENtkXYwGClRUIPN4DDNsoVH1Q-6:1731714220807
      source: https://discordapp.com/channels/1122455294988001363/1122581505693208596/1274407892472168488
    - name: Stock
      path: Tanks/German/E-100/Stock

- name: Tiger II
  type: Heavy
  tier: VIII
  nation: German 🍺
  remodels:
    - name: Schneide
      path: Tanks/German/Tiger-II/Schneide
      download: https://drive.usercontent.google.com/download?id=1jLOvOQfQzW_qteveHCbpSAvSWDXBpGAK&export=download&authuser=1&confirm=t&uuid=9c8a93d5-8609-406c-b52d-c5b0de531635&at=AENtkXaFUsgimhISqN6utSY7iAR5:1732362424834
      source: https://discordapp.com/channels/998886261005750354/998962868806483988/1279154399360581673
    - name: Defender
      path:
      download:
      source:
    - name: Stock
      path: Tanks/German/Tiger-II/Stock

#   E-50M:
#     Dreadnaught:
#       download: https://blitz-mods.com/mod/remodelings/remodeling-e50m-dreadnaught-273/download/pc-wg/file?_token=x=0
#       source: https://blitz-mods.com/mod/remodelings/remodeling-e50m-dreadnaught-273
#     Panzerbarracuda:
#       download: https://forblitz.ru/wp-content/uploads/2024/07/e50_m_panzerbarracuda_forblitz_05072024_pc.zip
#       source: https://forblitz.ru/modifications/remodelings/remodeling-e-50m-panzerbarracuda/20459
#     Nimmermer:
#       download: https://forblitz.ru/wp-content/uploads/2022/12/nimmermer_steam.zip
#       source: https://forblitz.ru/modifications/remodelings/remodeling-nimmermer-e-50m/14928

# mediums
- name: Leopard 1

  type: Medium
  tier: X
  nation: German 🍺
  remodels:
    - name: Mexas
      path: Tanks/German/Leopard-1/Mexas
      download: https://blitz-mods.com/mod/remodelings/remodeling-leopard-1-c2-mexas-209/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-leopard-1-c2-mexas-209
    - name: Reiter
      path: Tanks/German/Leopard-1/Reiter
      download: https://forblitz.ru/wp-content/uploads/2023/01/leopard1_reytar_steam.zip
      source: https://forblitz.ru/en/modifications/remodelings/rumodeling-leopard-1-reitar/15553
    - name: Mirny 13
      path: Tanks/German/Leopard-1/Mirny-13
      download: https://forblitz.ru/wp-content/uploads/2022/01/leopard1_qirashi_pc_dx11.zip
      source: https://forblitz.ru/en/modifications/remodelings/remodeling-leopard1/10540
    - name: 1a1
      path: Tanks/German/Leopard-1/1a1
      download: https://drive.usercontent.google.com/download?id=1Dcu7EMk4XMOplHd0EI6t-6-svzb9zxzr&export=download&authuser=1&confirm=t&uuid=86e4a6de-b474-4ca9-a769-6dab9e9e3dda&at=AENtkXZJ2vC1QouzEFmjgoAc4x2:1730989957853
      source: null
    - name: Lion
      path: Tanks/German/Leopard-1/Lion
      download: https://drive.usercontent.google.com/download?id=1MGLq4Vnd2rl9fOTw7ICaNPuBDIKY-MYG&export=download&authuser=1&confirm=t&uuid=572466e0-a84e-4690-a419-7d4805a6912b&at=AENtkXbVmafZScttTY6NUZnb62y:1730988335022
      source: null
    - name: Stock
      path: Tanks/German/Leopard-1/Stock

- name: Grille 15
  type: Td
  tier: X
  nation: German 🍺
  remodels:
    - name: Igelschnäuzchen
      path: Tanks/German/Grille-15/Igelschnäuzchen
      download: https://forblitz.ru/wp-content/uploads/2024/11/grille_15_igelschneutzchen_forblitz_061124_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-grille-15-igelschneutzchenen/21197
    - name: Erion
      path: Tanks/German/Grille-15/Erion
      download: https://drive.usercontent.google.com/download?id=1N7F7LzqTOu8vMpF_0N_6Dj9K3DuCUKhJ&export=download&authuser=1&confirm=t&uuid=9b59f4d2-770c-483f-b2ac-b1b2c03e4736&at=AIrpjvOmi8VbcjL6Pc6GKmPuZNXk:1736364228633
      source: https://blackwot.ru/2022/08/13/grille-15-erion/
    - name: Stock
      path: Tanks/German/Grille-15/Stock

#   Jp-E-100:

# France:
#   AMX-50B:
#     Charlesmartel:
#       download: https://drive.usercontent.google.com/download?id=1q02Uj4UX66ZFKjbTwulSn-Xec5fLHOt2&export=download&authuser=1&confirm=t&uuid=7bdcaa42-330a-4b90-bfa7-ca1ac645e6d7&at=AENtkXZVbEWPJbB6IKxIyRFTowb-:1730993378473
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1069655296995242004
#   AMX-M4-mle54:
#     Gascon:
#       download: https://tinyurl.com/y2jf7b2z
#       source: https://tinyurl.com/amx-gascon
#     Enhanced:
#       download: https://tinyurl.com/r6hkwmc8
#       source: https://tinyurl.com/m4mle54

#   AMX-30B:
#     Brenus:
#       download: https://tinyurl.com/brenus-download
#       source: https://tinyurl.com/brenus

- name: B-C 25 t
  type: Light
  tier: X
  nation: France 🥖
  remodels:
    - name: Arlequin Ter
      path: Tanks/France/B-C_25t/Arlequin-Ter
      download: https://blitz-mods.com/mod/remodelings/remodeling-bat-chatillon-25t-arlequin-ter-217/download/pc-wg/file?_token=x=0
      source: https://tinyurl.com/blitzmods
    - name: Marengo
      path: Tanks/France/B-C_25t/Marengo
      download: https://forblitz.ru/wp-content/uploads/2022/08/updated_batchat_25t_marengo_sadabsolution_steam.zip
      source: https://tinyurl.com/forblitz-marengo
    - name: Ignis Purgatio
      path: Tanks/France/B-C_25t/Ignis-Purgatio
      download: https://forblitz.ru/wp-content/uploads/2022/10/batchat_ignis_steam.zip
      source: https://tinyurl.com/ignis-purgatio
    - name: Foudre
      path: Tanks/France/B-C_25t/Foudre
      download: https://forblitz.ru/wp-content/uploads/2024/04/bat_chatillon25t_fdr_pc.zip
      source: https://tinyurl.com/bc25t-foudre
    - name: Stock
      path: Tanks/France/B-C_25t/Stock

- name: Foch 155
  type: Td
  tier: X
  nation: France 🥖
  remodels:
    - name: Eglantier
      path: Tanks/France/Foch-155/Eglantier
      download: https://blitz-mods.com/mod/remodelings/remodeling-foch-155-eglantier-253/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/remodeling-foch-155-eglantier-253
    - name: Stock
      path: Tanks/France/Foch-155/Stock

# Mediums
- name: Defender Mk.1
  type: Medium
  tier: VIII
  nation: GB 🌧️
  remodels:
    - name: Realistic
      path: Tanks/GB/Defender-Mk1/Realistic
      download: https://blitz-mods.com/mod/skins/skin-centurion-mkiii-ep-defender-167/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/skins/skin-centurion-mkiii-ep-defender-167
    - name: Stock
      path: Tanks/GB/Defender-Mk1/Stock

# Lights
- name: Vickers Light
  type: Light
  tier: X
  nation: GB 🌧️
  remodels:
    - name: Concept 5 The Unknown
      path: Tanks/GB/Vickers-Light/Concept-5-TheUnknown
      download: https://forblitz.ru/wp-content/uploads/2024/11/vikclight_concept5_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-concept-5-the-unknown/21206
    - name: Stock
      path: Tanks/GB/Vickers-Light/Stock

#TD's
- name: FV4005
  type: Td
  tier: X
  nation: GB 🌧️
  remodels:
    - name: King Flavius
      path: Tanks/GB/FV4005/King-Flavius
      download: https://blitz-mods.com/mod/remodelings/fv-4005-king-favius-259/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/remodelings/fv-4005-king-favius-259
    - name: Thunderchild
      path: Tanks/GB/FV4005/Thunderchild
      download: https://forblitz.ru/wp-content/uploads/2024/03/4005_thunderchild_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/animirovannyi-remodeling-fv4005-ditya-gro/19416
    - name: Galahad
      path: Tanks/GB/FV4005/Galahad
      download: https://forblitz.ru/wp-content/uploads/2022/02/fv4005_steam.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-gb83-4005-hd/10768
    - name: Stock
      path: Tanks/GB/FV4005/Stock
- name: FV215b 183
  type: Td
  tier: X
  nation: GB 🌧️
  remodels:
    - name: Tesla
      path: Tanks/GB/FV215b-183/Tesla
      download: https://forblitz.ru/wp-content/uploads/2023/12/fv215b183_tesla_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-fv215b-183/18768
    - name: Stock
      path: Tanks/GB/FV215b-183/Stock

# USSR:
#Heavy

- name: Obj. 268
  type: Td
  tier: X
  nation: USSR 🐻
  remodels:
    - name: Svyatogor
      path: Tanks/USSR/Obj.268/Svyatogor
      download: https://forblitz.ru/wp-content/uploads/2024/01/obj268_svyatogor_forblitz_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-obekt-268-svyatogor/18980
    - name: Alyosha Popovich
      path: Tanks/USSR/Obj.268/AlyoshaPopovich
      download: https://forblitz.ru/wp-content/uploads/2024/01/obj268_alesha_pc.zip
      source: https://forblitz.ru/modifications/remodelings/remodeling-obekt-268-alesha-popovich/19012
    - name: Stock
      path: Tanks/USSR/Obj.268/Stock
#   T-100LT:
#     Enhanced:
#       path: Tanks/USSR/T-100-LT/Enhanced/
#       download: https://drive.usercontent.google.com/download?id=1NJDaRzHvJY47Z69wTE_zqo7qwtxxxj7h&export=download&authuser=1&confirm=t&uuid=a6a51793-7d8a-46e6-b818-4377a324038f&at=AENtkXZ8rQFHRlrQeYgMq4Jhl9cZ:1730984861744
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1076705953262620733
#     Gyurza:
#       path: Tanks/USSR/T-100-LT/Gyurza/
#       download: https://forblitz.ru/wp-content/uploads/2023/12/t100lt_forblitz_pc.zip
#       source: https://forblitz.ru/modifications/remodelings/remodeling-t-100-lt-giurza/18808
#     Stock:
#       path: Tanks/USSR/T-100-LT/Stock/

# USA

# Heavy

#   T49:
#     Revenant:
#       download: ttps://drive.usercontent.google.com/download?id=1Osd9ShPOMmo5bQJnIbrk4V0eOvNW6pNV&export=download&authuser=0&confirm=t&uuid=1d38fb20-7343-49ab-a472-75b788541958&at=AENtkXb3Lpn9jO3poQl1YXPR3wGf:1730886397473
#       source: https://discord.com/channels/174448788436549632/254137952215498762/1011710957346619432

#   T30:
#     Assault-Kit:
#       download: https://forblitz.ru/wp-content/uploads/2022/08/updated_t30_countdown_sadabsolution_steam.zip
#       source: https://forblitz.ru/modifications/remodelings/remodeling-countdown-t30/13870
