- name: Mod packs
  remodels:
    - name: Deortep's BB modpack
      path: UI/Modpacks/DeortepBB
      download: https://forblitz.ru/wp-content/uploads/2024/11/dortebb-3.2_pc_wg.zip
      source: https://forblitz.ru/modifications/modpacks/dortebb-modpack-in-the-style-of-the-old-bb/21142
    - name: Rick's BB modpack
      path: UI/Modpacks/RickBBpack
      download: https://drive.usercontent.google.com/download?id=1dcTbSdNefhlNuI9Q83jlfpd0Ajzv8XBR&export=download&authuser=0&confirm=t&uuid=495657f4-ab74-4f29-86d6-4236e9064fc7&at=AIrpjvMWcygGls0o_7xq9qmZx9pH:17379075950341
      source: not provided
    - name: Stock
      path: UI/Stock
      load: false

- name: Battle UI elements
  remodels:
  - name: Coloured Minimap
    path: UI/Battle-UI/Colured-Minimap
    download: https://forblitz.ru/wp-content/uploads/2024/08/pc_bbminimap-1.zip
    source: https://forblitz.ru/modifications/interface/tsvetnye-mini-karty-v-stile-bb/20538
  - name: Minimap Radar
    path: UI/Battle-UI/Minimap-Radar
    download: https://forblitz.ru/wp-content/uploads/2022/12/radar_bb_steam-1.zip
    source: https://forblitz.ru/modifications/interface/radar-krugi-zasveta-na-mini-karte-iz-b/14972
  - name: 2.0 Ribbons
    path: UI/Battle-UI/Ribbons2.0
    download: https://blitz-mods.com/mod/user-interface/ribbons-20-by-zxcmashka-148/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/user-interface/ribbons-20-by-zxcmashka-148
  - name: Wot Ribbons
    path: UI/Battle-UI/WotRibbons
    download: https://drive.usercontent.google.com/download?id=1NT5TH8rm8yLu4MRKOjJA_3JYn6u_pAqx&export=download&authuser=1&confirm=t&uuid=4f320a2a-f83f-42fc-b99f-cfc34f74e8d7&at=APvzH3r3VvgcFnglqoenwOBfi12Z:1735811692159
    source: https://discord.com/channels/1137353382919675934/1307463765750714498/1307476239103295570
  - name: Wot 6th sense
    path: UI/Battle-UI/Wot-6th-Sense
    download: https://blitz-mods.com/mod/sixth-senses/bulb-sixth-sense-from-wot-pc-82/download/pc-wg/file?_token=x=0
    source: https://blitz-mods.com/mod/sixth-senses/orange-bulb-v2-41
  - name: Improved dirt
    path: UI/Battle-UI/Improved-Dirt
    download: https://drive.usercontent.google.com/download?id=1IWZrgKWXTzvscRhWhG5JF6qfH7zFA2BD&export=download&authuser=1&confirm=t&uuid=2b61de94-5284-47dc-8a36-ee63bacd30bb&at=AENtkXYh7Z-MAebx0Qljk1mS5SR0:1731192553712
    source: https://discord.com/channels/1122455294988001363/1122581505693208596/1124410812598079550
  - name: Coloured HitMarks
    path: UI/Battle-UI/Coloured-HitMarks
    download: https://drive.usercontent.google.com/download?id=1LCDd76xWmLX5QYLcpCw_5fNjaB_7dU6D&export=download&authuser=1&confirm=t&uuid=89c63b0d-8862-4b15-b726-631310d4958e&at=APvzH3oXXhyoZchLtf_ygLiAYQNK:1735653594722
    source: https://discord.com/channels/1122455294988001363/1122581505693208596/1124410812598079550
  - name: White tank destroyed
    path: UI/Battle-UI/White-Destroyed
    download: https://drive.usercontent.google.com/download?id=18r3Quf4qWESemoP-54zxutn566oE9MO8&export=download&authuser=1&confirm=t&uuid=ae2c04e5-2bbd-4c0b-b56d-7ff95fed93b9&at=APvzH3qRk93326qfr1wfIHh7nzDY:1736164869195
    source: https://discord.com/channels/1122455294988001363/1122581505693208596/1124410812598079550
  - name: Zoom Out
    path: UI/Battle-UI/Zoom-Out
    download: https://drive.usercontent.google.com/download?id=1vM3qcIqWT5H7vki-qzsGICn8LaXHUYau&export=download&authuser=1&confirm=t&uuid=4081bfb4-7a85-4f1b-a530-330c4b6e4cba&at=APvzH3r2gB8I4DOKQnr6imH_xryl:1735997097603
    source: null
  - name: Ears
    path: UI/Battle-UI/Ears
    download: https://forblitz.ru/wp-content/uploads/2022/03/ears_steam_9_6_pc.zip
    source: https://forblitz.ru/modifications/interface/interface-ears/11299
  - name: Info Panel
    path: UI/Battle-UI/Info-Panel
    download: https://forblitz.ru/wp-content/uploads/2022/02/panel_exp_rebuld_pc.zip
    source: https://forblitz.ru/modifications/interface/info-panel-expanding-warfare/10657
  - name: Stock
    path: UI/Stock
    load: false

- name: Lobby UI elements
  remodels:
    - name: Extended Tech Tree
      path: UI/Lobby-UI/Extended-tech-tree
      download: https://blitz-mods.com/mod/user-interface/wg-extended-tech-tree-90/download/pc-wg/file?_token=x=0
      source: https://blitz-mods.com/mod/user-interface/wg-extended-tech-tree-90
    - name: Wot Shells
      path: UI/Lobby-UI/Wot-Shells
      download: https://forblitz.ru/wp-content/uploads/2023/10/shells_bb_pc_10_7.zip
      source: https://forblitz.ru/modifications/interface/ikonki-snaryadov-iz-bb/14633
    - name: Wot Equipement
      path: UI/Lobby-UI/Wot-Equipement
      download: https://forblitz.ru/wp-content/uploads/2023/10/optional_devices_bb_pc_10_7.zip
      source: https://forblitz.ru/modifications/interface/ikonki-hd-oborudovanie-iz-world-of-tanks/14581
    - name: Wot Modules
      path: UI/Lobby-UI/Wot-Modules
      download: https://forblitz.ru/wp-content/uploads/2024/08/hd1_modules_bb_pc.zip
      source: https://forblitz.ru/modifications/interface/hd-moduli-v-dereve-razvitii-iz-bb/14611
    - name: Random Tank Picker
      path: UI/Lobby-UI/Random-tank-picker
      download: https://forblitz.ru/wp-content/uploads/2024/02/randomtankbutton_pc_wg.zip
      source: https://forblitz.ru/modifications/interface/knopka-vybora-sluchainogo-tanka-tolk/19085
    - name: Replace Rank with mastery badges
      path: UI/Lobby-UI/RankToMastery
      download: https://forblitz.ru/wp-content/uploads/2024/01/ranktomastery_pc_wg.zip
      source: https://forblitz.ru/modifications/interface/zamena-rangov-na-masterstvo/18989
    - name: Blitz Stats
      path: UI/Lobby-UI/BlitzStats
      download: https://get.blitzinsider.com/blitz-insider-session-mod-pc-11.6.0_2025-01-23-15-50.zip
      source: https://discord.com/channels/1278635245700120630/1279016368548872233/1279016785185869907
    - name: Carousel with statistic
      path: UI/Lobby-UI/Statistic-Carousel
      download: https://forblitz.ru/wp-content/uploads/2024/10/carousel-stats-wg-pc.zip
      source: https://forblitz.ru/modifications/interface/statistics-in-the-carousel/20781
    - name: Compact Storage
      path: UI/Lobby-UI/Compact-Storage
      download: https://forblitz.ru/wp-content/uploads/2024/02/compactstorage_pc_wg.zip
      source: https://forblitz.ru/modifications/interface/kompaktnoe-khranilishche/19185
    - name: Wot Boosters
      path: UI/Lobby-UI/Wot-Boosters
      download: https://forblitz.ru/wp-content/uploads/2023/10/bb_boosters_icons_pc_10_7.zip
      source: https://forblitz.ru/modifications/interface/ikonki-busterov-iz-bb/14871
    - name: Stock
      path: UI/Stock
      load: false


# Other:
#   Camo:
#     Camo-unlocker:
#       path: Other/Camo/Camo-unlocker/
#       download: https://blitz-mods.com/mod/camouflages/fake-legendary-camouflages-for-wotb-1142-274/download/pc-wg/file?_token=x=0
#       source: https://blitz-mods.com/mod/camouflages/fake-legendary-camouflages-for-wotb-1142-274
#     Stock:
#       path: Other/Stock/